#!/bin/bash

sudo echo -n "1-2:1.0" > /sys/bus/usb/drivers/ftdi_sio/unbind
sudo echo -n "3-2:1.0" > /sys/bus/usb/drivers/ftdi_sio/unbind
sudo echo -n "1-2:1.0" > /sys/bus/usb/drivers/usbfs/bind
sudo echo -n "3-2:1.0" > /sys/bus/usb/drivers/usbfs/bind